### ISSUE TITLE
mirror.serverion.com rsync fails

### ISSUE THREAD

**Issue by zeha** [grml/grml-mirrors#23]
```
% rsync rsync://mirror.serverion.com/grml
@ERROR: Unknown module 'grml'
rsync error: error starting client-server protocol (code 5) at main.c(1863) [Receiver=3.2.7]
```

**Comment by mika** [comment]
Ping @ServerionNL :)

**Comment by ServerionNL** [comment]
Please try again!

`[root@mirror html]# rsync rsync://mirror.serverion.com/grml
drwxrwsr-x          4,096 2024/08/17 19:19:05 .
-rwxrwxr-x          2,505 2022/11/11 23:55:24 .download.sh
-rw-r--r--          8,330 2024/08/17 19:13:18 .old.index.de.html
-rw-r--r--          8,112 2024/08/17 19:13:24 .old.index.en.html
-rw-r--r--            859 2024/02/27 12:06:38 SHA256SUMS
-rw-r--r--            833 2024/02/27 12:06:38 SHA256SUMS.gpg
-rw-r--r--            859 2022/11/29 11:45:44 SHA256SUMS_2022.11
-rw-r--r--            833 2022/11/29 11:46:34 SHA256SUMS_2022.11.gpg
-rw-r--r--          2,238 2004/09/19 16:35:32 favicon.ico
-rw-r--r--        220,210 2024/02/05 12:21:06 gnupg-michael-prokop.txt
-rw-r--r--    863,240,192 2022/11/29 08:38:20 grml32-full_2022.11.iso
-rw-r--r--            833 2022/11/29 11:44:01 grml32-full_2022.11.iso.asc
-rw-r--r--    900,988,928 2024/02/26 17:44:51 grml32-full_2024.02.iso
-rw-r--r--            833 2024/02/27 12:05:48 grml32-full_2024.02.iso.asc
-rw-r--r--             90 2024/02/26 17:44:51 grml32-full_2024.02.iso.sha256
-rw-r--r--    474,218,496 2022/11/29 08:47:22 grml32-small_2022.11.iso
-rw-r--r--            833 2022/11/29 11:44:08 grml32-small_2022.11.iso.asc
-rw-r--r--    480,509,952 2024/02/26 17:30:12 grml32-small_2024.02.iso
-rw-r--r--            833 2024/02/27 12:05:48 grml32-small_2024.02.iso.asc
-rw-r--r--             91 2024/02/26 17:30:12 grml32-small_2024.02.iso.sha256
-rw-r--r--    896,794,624 2022/11/29 08:22:33 grml64-full_2022.11.iso
-rw-r--r--            833 2022/11/29 11:44:18 grml64-full_2022.11.iso.asc
-rw-r--r--    959,709,184 2024/02/26 17:20:19 grml64-full_2024.02.iso
-rw-r--r--            833 2024/02/27 12:05:48 grml64-full_2024.02.iso.asc
-rw-r--r--             90 2024/02/26 17:20:19 grml64-full_2024.02.iso.sha256
-rw-r--r--    516,161,536 2022/11/29 08:07:27 grml64-small_2022.11.iso
-rw-r--r--            833 2022/12/01 10:03:06 grml64-small_2022.11.iso.asc
-rw-r--r--    532,938,752 2024/02/26 17:55:31 grml64-small_2024.02.iso
-rw-r--r--            833 2024/02/27 12:05:48 grml64-small_2024.02.iso.asc
-rw-r--r--             91 2024/02/26 17:55:31 grml64-small_2024.02.iso.sha256
-rw-r--r--  1,734,606,848 2022/11/29 10:47:21 grml96-full_2022.11.iso
-rw-r--r--            833 2022/11/29 11:44:38 grml96-full_2022.11.iso.asc
-rw-r--r--  1,832,878,080 2024/02/27 10:37:41 grml96-full_2024.02.iso
-rw-r--r--            833 2024/02/27 12:05:48 grml96-full_2024.02.iso.asc
-rw-r--r--    963,641,344 2022/11/29 11:17:18 grml96-small_2022.11.iso
-rw-r--r--            833 2022/11/29 11:44:48 grml96-small_2022.11.iso.asc
-rw-r--r--    984,612,864 2024/02/27 10:28:43 grml96-small_2024.02.iso
-rw-r--r--            833 2024/02/27 12:05:48 grml96-small_2024.02.iso.asc
-rw-r--r--     41,605,120 2022/11/29 08:38:28 grml_netboot_package_grml32-full_2022.11.tar
-rw-r--r--     42,250,240 2024/02/26 17:45:03 grml_netboot_package_grml32-full_2024.02.tar
-rw-r--r--            111 2024/02/27 12:07:34 grml_netboot_package_grml32-full_2024.02.tar.sha256
-rw-r--r--     56,350,720 2022/11/29 08:22:39 grml_netboot_package_grml64-full_2022.11.tar
-rw-r--r--     59,893,760 2024/02/26 17:20:30 grml_netboot_package_grml64-full_2024.02.tar
-rw-r--r--            111 2024/02/26 17:20:30 grml_netboot_package_grml64-full_2024.02.tar.sha256
-rw-r--r--  2,835,277,620 2022/11/29 09:28:40 grml_sources-2022.11.tar.gz
-rw-r--r--             70 2022/11/29 09:29:31 grml_sources-2022.11.tar.gz.sha1
-rw-r--r--  3,070,381,653 2024/02/27 11:06:49 grml_sources-2024.02.tar.gz
-rw-r--r--             70 2024/02/27 11:07:43 grml_sources-2024.02.tar.gz.sha1
-rw-r--r--          6,582 2024/08/17 19:18:39 index.de.html
-rw-r--r--          6,451 2024/08/17 19:19:05 index.en.html
-rw-r--r--             11 2024/10/14 12:17:01 timestamp.txt
drwxr-sr-x          4,096 2024/02/05 12:18:26 devel
[root@mirror html]# `
