### ISSUE TITLE
mirror.lagis.at ftp fails

### ISSUE THREAD

**Issue by zeha** [grml/grml-mirrors#25]
mirmon shows that ftp on mirror.lagis.at does not work. I have a hard time verifying this, due to lack of a good FTP client and a network allowing it.

lftp seems to time out after login:
```
% lftp mirror.lagis.at
lftp mirror.lagis.at:~> ls
`ls' at 0 [Making data connection...]
```

Not sure it's still worth spending time on FTP. Should we just drop it?

**Comment by mika** [comment]
Confirmed:

```
ncftp / > ls
Data connection timed out.
````

Agree, let's scratch FTP at least for lagis.at :)
